version: "3.7"
services:
  benzinpriser:
    image: registry.bjarke.xyz/benzinpriser
    build:
      context: ./
    secrets:
      - env
    networks:
      - swarm-overlay

networks:
  swarm-overlay:
    external: true
    name: swarm-overlay

secrets:
  env:
    file: .env
