// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Image struct {
	Src  string `json:"src"`
	Type string `json:"type"`
	Size int    `json:"size"`
	Name string `json:"name"`
}

type NewRecipe struct {
	Title       string  `json:"title"`
	Description *string `json:"description"`
}
