apiVersion: v1
kind: Namespace
metadata:
  name: fuelprices
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fuelpricesapi
  namespace: fuelprices
spec:
  selector:
    matchLabels:
      app: fuelpricesapi
  template:
    metadata:
      labels:
        app: fuelpricesapi
    spec:
      containers:
        - name: fuelpricesapi
          image: registry.bjarke.xyz/fuelpricesapi
          env:
            - name: PORT
              value: "80"
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: fuelpricesapi-service
  namespace: fuelprices
spec:
  selector:
    app: fuelprices
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fuelpricesapi-ingress
  namespace: fuelprices
  annotations:
    kubernetes.io/ingress.class: nginx fuelpricesapi-ingress
spec:
  rules:
    - host: fuelprices-api.bjarke.xyz
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: fuelpricesapi-service
                port:
                  number: 80
  tls:
    - hosts:
        - whoami.bjarke.xyz
      secretName: default-cert-tls
