version: "3.8"

services:
  redis:
    image: redis:alpine
    command: redis-server --requirepass PASSWORD
    ports:
      - "6379:6379"
  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=shoppinglist
