name: Deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install
      - run: npm test
        id: test
      - name: Notify on error
        uses: Ilshidur/action-discord@0.3.2
        if: failure() && steps.test.outcome == 'failure'
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: "⚠️ {{ EVENT_PAYLOAD.repository.full_name }} tests failed. <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}>"

  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: cloudflare/wrangler-action@1.3.0
        name: Publish
        id: publish
        with:
          preCommands: |
            cp wrangler.toml.example wrangler.toml
            sed -i 's/PROD_KV_ID/${{ secrets.CF_FUELPRICES_KV_ID }}/' wrangler.toml
            sed -i 's/CACHEREFRESHKEY-REPLACEME/${{ secrets.CACHE_REFRESH_KEY }}/' wrangler.toml
            sed -i 's/MQURL-REPLACEME/${{ secrets.MQ_URL }}/' wrangler.toml
            sed -i 's/MQVHOST-REPLACEME/${{ secrets.MQ_VHOST }}/' wrangler.toml
            sed -i 's/MQEXCHANGE-REPLACEME/${{ secrets.MQ_EXCHANGE }}/' wrangler.toml
            sed -i 's/MQUSER-REPLACEME/${{ secrets.MQ_USER }}/' wrangler.toml
            sed -i 's/MQPASS-REPLACEME/${{ secrets.MQ_PASS }}/' wrangler.toml
          apiToken: ${{ secrets.CF_WORKER_TOKEN }}
          environment: 'production'
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
      - name: Notify on error
        uses: Ilshidur/action-discord@0.3.2
        if: failure() && steps.publish.outcome == 'failure'
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: "⚠️ {{ EVENT_PAYLOAD.repository.full_name }} failed to release. <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}>"
      - name: Notify on success
        uses: Ilshidur/action-discord@0.3.2
        if: success() && steps.publish.outcome == 'success'
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: "🚀 {{ EVENT_PAYLOAD.repository.full_name }} has been released. <https://github.com/${{ github.repository }}/>"
