name: Deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install
      - run: npm test
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: cloudflare/wrangler-action@1.3.0
        name: Publish
        with:
          preCommands: |
            cp wrangler.toml.example wrangler.toml
            sed -i 's/PROD_KV_ID/${{ secrets.CF_FUELPRICES_KV_ID }}/' wrangler.toml
            sed -i 's/CACHEREFRESHKEY-REPLACEME/${{ secrets.CACHE_REFRESH_KEY }}/' wrangler.toml
          apiToken: ${{ secrets.CF_WORKER_TOKEN }}
          environment: 'production'
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
